additional-dependency-files:
  - type: maven-pom-xml
    path: application/jaxrs-activemq-quarkus/pom.xml
  - type: maven-pom-xml
    path: application/implementer-grpc-quarkus/pom.xml
  - type: maven-pom-xml
    path: application/redis-mysql-helidon/pom.xml
  - type: maven-pom-xml
    path: application/web-java-spring/pom.xml
  - type: maven-pom-xml
    path: application/consumer-redis-quarkus/pom.xml
  - type: maven-pom-xml
    path: application/jaxrs-cassandra-quarkus/pom.xml
  - type: maven-pom-xml
    path: application/jaxrs-memcached-quarkus/pom.xml
  - type: maven-pom-xml
    path: application/jaxrs-mongodb-quarkus/pom.xml
  - type: maven-pom-xml
    path: application/jaxrs-hazelcast-quarkus/pom.xml
  - type: maven-pom-xml
    path: application/consumer-kafka-quarkus/pom.xml
  - type: maven-pom-xml
    path: application/jaxrs-rabbitmq-quarkus/pom.xml
  - type: maven-pom-xml
    path: application/randompublish-quarkus/pom.xml
  - type: maven-pom-xml
    path: application/consumer-hazelcast-quarkus/pom.xml
  - type: maven-pom-xml
    path: application/jaxrs-mysql-quarkus/pom.xml
  - type: maven-pom-xml
    path: application/parent-pom/pom.xml
  - type: maven-pom-xml
    path: application/scheduled-quarkus/pom.xml
  - type: maven-pom-xml
    path: application/web-java-openliberty/pom.xml
  - type: maven-pom-xml
    path: application/consumer-activemq-quarkus/pom.xml
  - type: maven-pom-xml
    path: application/jaxrs-redis-quarkus/pom.xml
  - type: maven-pom-xml
    path: application/consumer-rabbitmq-quarkus/pom.xml
  - type: maven-pom-xml
    path: application/producer-kafka-quarkus/pom.xml
  - type: maven-pom-xml
    path: application/jaxrs-postgres-quarkus/pom.xml
  - type: maven-pom-xml
    path: application/webapp-service/pom.xml
  - type: maven-pom-xml
    path: application/jaxrs-kafka-quarkus/pom.xml
ignore-failures:
  java:
    - com.whalin/Memcached-Java-Client
    - org.glassfish/javax.json
    - org.hamcrest/hamcrest-all
rules-config:
  no-recent-package-release:
    fail-at-months: 48
  no-recent-commit:
    fail-at-months: 48
