docker:
  - "(docker|Dockerfile)"
docs:
  - "docs"
github-action:
  - "(github action|github-action)"
java:
  - "java"
javascript:
  - "(javascript|js)"
kind:
  - "kind"
kubernetes:
  - "kubernetes"
minikube:
  - "minikube"
openshift:
  - "openshift"
quarkus:
  - "quarkus"
security vulnerability:
  - "vulnerability"
bug:
  - "(bug|error|Exception|alert)"
