# Directory pattern
cicd:
  - changed-files:
      - any-glob-to-any-file: .github/**/*
docs:
  - changed-files:
      - any-glob-to-any-file: 
          - docs/**/*
          - "**/*.md"
github-action:
  - changed-files:
      - any-glob-to-any-file:  .github/**/*
java:
  - changed-files:
      - any-glob-to-any-file:
          - application/**/*
          - "**/*.java"
javascript:
  - changed-files:
      - any-glob-to-any-file: 
          - application/**/*.js
          - "**/*.js"
kubernetes:
  - changed-files:
      - any-glob-to-any-file: kubernetes/**/*
quarkus:
  - changed-files:
      - any-glob-to-any-file: application/*-quarkus/*
docker:
  - changed-files:
      - any-glob-to-any-file: "**/Dockerfile"
kind:
  - changed-files:
      - any-glob-to-any-file: "**/kind-*"
minikube:
  - changed-files:
      - any-glob-to-any-file:  "**/minikube-*"
