package org.acme.getting.started;

import com.datastax.oss.driver.api.mapper.annotations.DaoFactory;
import com.datastax.oss.driver.api.mapper.annotations.Mapper;

/**
 * An object mapper defining all the DAOs for this application.
 *
 * <p>The mapper is the main entry point for the DataStax Java driver object mapper. Instances of
 * this interface should be created using {@link FruitMapperBuilder}; this builder is automatically
 * generated by the object mapper.
 *
 * @see <a
 *     href="https://docs.datastax.com/en/developer/java-driver/latest/manual/mapper/mapper/">Using
 *     the Mapper interface</a>
 */
@Mapper
public interface FruitMapper {

  /**
   * Creates a new {@link FruitDao}. It will operate on the same keyspace as the Quarkus session.
   *
   * @return a new {@link FruitDao}.
   */
  @DaoFactory
  FruitDao fruitDao();
}
