kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cassandra-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: cassandra
  selector:
    matchLabels:
      name: cassandra-hostpath
