kind: PersistentVolume
apiVersion: v1
metadata:
  name: cassandra-pv
  labels:
    name: cassandra-hostpath
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: cassandra
  hostPath:
    path: /data/pv012
