apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-kafka-quarkus
spec:
  selector:
    matchLabels:
      app: producer-kafka-quarkus
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tier: frontend
        component: quarkus
        app: producer-kafka-quarkus
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: producer-kafka-quarkus
          image: yurak/producer-kafka-quarkus:latest@sha256:92de7eed29032aa368205bc77374b932a1ae3b614e112b1d6e616ac4004bfda8
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /q/health/live
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              port: 8080
              path: /q/health/ready
            initialDelaySeconds: 10
            periodSeconds: 30
