{
 "title": "Liberty-Metrics-G5-20190521",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "app", "label": "app", "query": "base:cpu_available_processors" },
   {
    "name": "servlet",
    "query": "{__name__=~\"vendor:servlet.*_response_time_total_seconds\",app=~`[[app]]`}"
   },
   {
    "name": "dur",
    "label": "moving average",
    "query": "[1m],[5m],[10m],[30m],[1h],[1d],[7d]"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Available CPU Processors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_cpu_availableProcessors{app=~`[[app]]`}",
     "legendFormat": "app: {{app}}, instance: {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load Percent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad_percent{app=~`[[app]]`}",
     "legendFormat": "app: {{app}}, instance: {{instance}}"
    }
   ]
  },
  {
   "title": "CPU System Load Average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_cpu_systemLoadAverage{app=~`[[app]]`}",
     "legendFormat": "app: {{app}}, instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Maximum Heap Size",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "base_memory_maxHeap_bytes{app=~`[[app]]`}"
      }
     ]
    },
    {
     "title": "Heap Usage Percentage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(base_memory_usedHeap_bytes{app=~`[[app]]`}/base_memory_maxHeap_bytes{app=~`[[app]]`})",
       "legendFormat": "app: {{app}}, instance: {{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Servlets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Request Count",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{__name__=~\"vendor_servlet.*_request_total\",app=~`[[app]]`}"
    }
   ]
  },
  {
   "title": "Request Count for [[servlet]]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_servlet_request_total{app=~`[[app]]`}",
     "legendFormat": "app: {{app}}, instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Response Time for [[servlet]] [[dur]] moving average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(vendor_servlet_responseTime_total_seconds{app=~`[[app]]`}[[dur]])/rate(vendor_servlet_request_total{app=~`[[app]]`}[[dur]])",
     "legendFormat": "app: {{app}}, instance: {{instance}}"
    }
   ]
  },
  { "title": "Connection Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Free Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"vendor_connectionpool_free_connections\",app=~`[[app]]`}",
     "legendFormat": "name: {{__name__}} app: {{app}}, instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Connection Handles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"vendor_connectionpool_connection_handles\",app=~`[[app]]`}",
     "legendFormat": "name: {{__name__}} app: {{app}}, instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Create Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"vendor_connectionpool_create_total\",app=~`[[app]]`}",
     "legendFormat": "name: {{__name__}} app: {{app}}, instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Destroy Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"vendor:connectionpool_.*_destroy_total\",app=~`[[app]]`}",
     "legendFormat": "name: {{__name__}} app: {{app}}, instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Managed Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"vendor:connectionpool_.*_managed_connections\",app=~`[[app]]`}",
     "legendFormat": "name: {{__name__}} app: {{app}}, instance: {{instance}}"
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Active Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"vendor_session_active_sessions\",app=~`[[app]]`}",
     "legendFormat": "name: {{__name__}} app: {{app}}, instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Live  Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"vendor:session_.*_live_sessions\",app=~`[[app]]`}",
     "legendFormat": "name: {{__name__}} app: {{app}}, instance: {{instance}}"
    }
   ]
  },
  { "title": "Threadpools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Active Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"vendor:threadpool_.*_active_threads\",app=~`[[app]]`}",
     "legendFormat": "name: {{__name__}} app: {{app}}, instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Threadpool Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"vendor:threadpool_.*_size\",app=~`[[app]]`}",
     "legendFormat": "name: {{__name__}} app: {{app}}, instance: {{instance}}"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Time per Global GC Cycle [[dur]] moving average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(base_gc_time_seconds{app=~`[[app]]`}[[dur]]) / rate(base_gc_total{app=~`[[app]]`}[[dur]])",
     "legendFormat": "app: {{app}}, instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Time per Scavenge GC Cycle [[dur]] moving average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(base_gc_time_seconds{app=~`[[app]]`}[[dur]]) / rate(base_gc_total{app=~`[[app]]`}[[dur]])",
     "legendFormat": "app: {{app}}, instance: {{instance}}"
    }
   ]
  },
  { "title": "Other JVM Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "JVM Uptime",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "base_jvm_uptime_seconds{app=~`[[app]]`}"
    },
    {}
   ]
  }
 ]
}