{
 "title": "Quarkus dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "RandomResource Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_webapp_tier_resource_RandomResource_performedChecks_total",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "RandomResource Highest So Far",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "application_webapp_tier_resource_RandomResource_checksTimer_seconds_count"
    }
   ]
  },
  {
   "title": "RandomResource Performance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_webapp_tier_resource_RandomResource_checksTimer_seconds ",
     "legendFormat": "{{quantile }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "base_memory_maxHeap_bytes{app=\"randompublish-quarkus\"}",
     "legendFormat": "{{ app }}"
    }
   ]
  }
 ]
}