apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
spec:
  rules:
    - host: k8s.3tier.webapp
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: wlp
                port:
                  number: 9080
          - path: /quarkus/activemq
            pathType: Prefix
            backend:
              service:
                name: jaxrs-activemq-quarkus
                port:
                  number: 8080
          - path: /quarkus/hazelcast
            pathType: Prefix
            backend:
              service:
                name: jaxrs-hazelcast-quarkus
                port:
                  number: 8080
          - path: /quarkus/kafka
            pathType: Prefix
            backend:
              service:
                name: jaxrs-kafka-quarkus
                port:
                  number: 8080
          - path: /quarkus/memcached
            pathType: Prefix
            backend:
              service:
                name: jaxrs-memcached-quarkus
                port:
                  number: 8080
          - path: /quarkus/mongodb
            pathType: Prefix
            backend:
              service:
                name: jaxrs-mongodb-quarkus
                port:
                  number: 8080
          - path: /quarkus/mysql
            pathType: Prefix
            backend:
              service:
                name: jaxrs-mysql-quarkus
                port:
                  number: 8080
          - path: /quarkus/postgres
            pathType: Prefix
            backend:
              service:
                name: jaxrs-postgres-quarkus
                port:
                  number: 8080
          - path: /quarkus/rabbitmq
            pathType: Prefix
            backend:
              service:
                name: jaxrs-rabbitmq-quarkus
                port:
                  number: 8080
          - path: /quarkus/redis
            pathType: Prefix
            backend:
              service:
                name: jaxrs-redis-quarkus
                port:
                  number: 8080
          - path: /quarkus/cassandra
            pathType: Prefix
            backend:
              service:
                name: jaxrs-cassandra-quarkus
                port:
                  number: 8080
          - path: /quarkus/grpc
            pathType: Prefix
            backend:
              service:
                name: jaxrs-grpc-quarkus
                port:
                  number: 8080
