apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaxrs-grpc-quarkus
spec:
  selector:
    matchLabels:
      app: jaxrs-grpc-quarkus
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        tier: frontend
        component: quarkus
        app: jaxrs-grpc-quarkus
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: jaxrs-grpc-quarkus
          image: yurak/jaxrs-grpc-quarkus:latest@sha256:017ea22a79f5928ac086a940dd12a9aa018f5c104b3cf69d707b33e7aeba6166
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 9000
          livenessProbe:
            httpGet:
              port: 8080
              path: /q/health/live
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              port: 8080
              path: /q/health/ready
            initialDelaySeconds: 10
            periodSeconds: 30
