apiVersion: v1
kind: Service
metadata:
  name: implementer-grpc-quarkus
spec:
  type: ClusterIP
  selector:
    app: implementer-grpc-quarkus
  ports:
    - name: http
      protocol: TCP
      port: 8080
    - name: grpc-server
      protocol: TCP
      port: 9000
