apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-grpc-quarkus
spec:
  selector:
    matchLabels:
      app: server-grpc-quarkus
  replicas: 1
  template:
    metadata:
      labels:
        tier: frontend
        component: quarkus
        app: server-grpc-quarkus
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: server-grpc-quarkus
          image: yurak/server-grpc-quarkus:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 9000
          livenessProbe:
            httpGet:
              port: 8080
              path: //q/health/live
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              port: 8080
              path: //q/health/ready
            initialDelaySeconds: 10
            periodSeconds: 30
