apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
type: Opaque
data:
  mysql-password: d2ViYXBw
  pg-password: d2ViYXBw
  artemis-password: c2ltZXRyYWVoY2FwYQ==
  rabbitmq-password: b3NzYXBs
