name: Assign issues to project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v2.0.0
        with:
          project-url: https://github.com/users/yurake/projects/1/views/1
          github-token: ${{ secrets.PAT_GITHUB_ACTION_WORKFLOW }}
