on:
  pull_request:
    types: [opened]
name: Pull Request opened
jobs:
  assignToProject:
    name: Assign PullRequest to Project
    runs-on: ubuntu-latest
    steps:
      - name: Assign PullRequest to Project
        uses: technote-space/create-project-card-action@1c70cc58ecee907bc9544f02cc2a4171a291705c # v1.4.2
        with:
          PROJECT: Feature request
          COLUMN: In progress
